[package]
name = "frost-dalek-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
frost-dalek = "0.2.3"
log = "0.4.22"
